//
//  User.swift
//  IHeartRate WatchKit Extension
//
//  Created by Bryce Schmisseur on 2/3/21.
//
//  Creates a user object model to store all the properties of the user

import UIKit

///A user object model to store all the properties of the user
class User: NSObject {
    
    //MARK: Properties
    
    var id: String //id generated by Apple's oAuth request
    var fullName: String? // First and last name of the user
    var email: String? // email associated with the user's apple id account
    
    //MARK: Initialization
    
    ///Initialization method of the `User` object
    /// ```
    /// self.id = id //id generated by Apple's oAuth request
    /// self.fullName = fullName // First and last name of the user
    /// self.email = email // email associated with the user's apple id account
    /// ```
    /// - warning: The parameters must not be null
    /// - parameters:
    ///     - id: id generated by Apple's oAuth request
    ///     - fullName: First and last name of the user
    ///     - email: email associated with the user's apple id account
    init(id: String, fullName: String, email: String){
        
        self.id = id
        self.fullName = fullName
        self.email = email
    }
    
    ///Initialization method of the `User` object for returning users
    /// ```
    /// self.id = id //id generated by Apple's oAuth request
    /// ```
    /// - warning: The parameters must not be null
    /// - parameters:
    ///     - id: id generated by Apple's oAuth request
    init(id: String) {
        self.id = id
        self.fullName = "previous user"
        self.email = ""
    }
    
    //MARK: Methods
    
    /// This function is used for testing in order to log the `Heart Rate` object information to the console
    /// 
    /// - Returns: Logs out the user information within the object using NSLog
    func toString() {
        NSLog("User Information \n\t ID: \(self.id) \n\t Full Name: \(String(describing: self.fullName)) \n\t Email: \(String(describing: self.email))")
    }

}
